spring:
  application:
    name: v-backend
  datasource:
    url: jdbc:mysql://localhost:3306/v_app?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: SIva@7482
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate # We use schema.sql, so just validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
#  sql:
#    init:
#      mode: always # Initialize schema.sql if needed (usually handled manually or via flyway, but for this task we can use spring.sql.init)
#      schema-locations: file:../db/schema.sql

# JWT Configuration
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 1 day
  refresh-expiration: 604800000 # 7 days

server:
  port: 8080
  servlet:
    context-path=/v-app
  error:
    include-message: always
